CREATE DATABASE IF NOT EXISTS FSEBVU;
DEFAULT CHARACTER SET utf8mb4;
COLLATE utf8mb4_general_ci;

USE FSEBVU;

CREATE TABLE usuario(
codigo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome_usuario VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(60) NOT NULL,
senha VARCHAR(32) NOT NULL
);

CREATE TABLE admin(
codigo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome_admin VARCHAR(50) NOT NULL UNIQUE,
email_admin VARCHAR(60) NOT NULL,
senha_admin VARCHAR(32) NOT NULL
);

CREATE TABLE post_receita(
codigo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome_usuario VARCHAR(50) NOT NULL FOREIGN KEY 
REFERENCES usuario(nome_usuario),
data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
hora INT TIMESTAMP NOT NULL,
titulo VARCHAR(50) NOT NULL,
descricao VARCHAR(300) NOT NULL,
ingredientes VARCHAR(600) NOT NULL,
modo_de_preparo VARCHAR(1000) NOT NULL,
);

CREATE TABLE site(
codigo INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE site_post_receita(
codigo INT NOT NULL FOREIGN KEY REFERENCES site(codigo),
codigo INT NOT NULL FOREIGN KEY REFERENCES post_receita(codigo),
);